# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      USE_APPROVALS: 
        description: Enable approvals?
        type: choice
        options:
          - 'true'
          - 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  initialize:
    name: Initialize Workflow
    runs-on: ubuntu-latest
    steps:
      - if: ${{inputs.ACCESS=='true'}}
        run: echo "Initialize Workflow"
        shell: bash
        
  approval:
    name: Approve Workflow Deployment
    runs-on: ubuntu-latest
    if: ${{ inputs.USE_APPROVALS == 'true' }}
    environment: approval-environment
    steps:
      - name: Approve Workflow Deployment
        run: echo "Approved Workflow Deployment"
        shell: bash

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [approval]
    if: ${{ !failure() && !cancelled() }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. ${{needs.approval.result}}
