name: Print Outputs of All Jobs

on:
  workflow_dispatch:

jobs:
  # First job to set some outputs
  job1:
    name: First Job
    runs-on: ubuntu-latest
    outputs:
      key1: ${{ steps.set_output.outputs.key1 }}
      key2: ${{ steps.set_output.outputs.key2 }}
    steps:
      - name: Set Outputs
        id: set_output
        run: |
          echo "key1=Value1" >> $GITHUB_OUTPUT
          echo "key2=Value2" >> $GITHUB_OUTPUT

  # Second job to set additional outputs
  job2:
    name: Second Job
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      key3: ${{ steps.set_output.outputs.key3 }}
    steps:
      - name: Set Output
        id: set_output
        run: |
          echo "key3=Value3" >> $GITHUB_OUTPUT

  # Job to print all outputs
  print_outputs:
    name: Print All Outputs
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Print Outputs from Job1
        run: |
          echo "Job1 Outputs:"
          echo "Key1: ${{ needs.job1.outputs.key1 }}"
          echo "Key2: ${{ needs.job1.outputs.key2 }}"

      - name: Print Outputs from Job2
        run: |
          echo "Job2 Outputs:"
          echo "Key3: ${{ needs.job2.outputs.key3 }}"
